### ISSUE TITLE
Meta: what to do?

### ISSUE THREAD

**Issue by justinrlle** [ShinGecko/neKo-Api#1]
This is a kind off roadmap for this project. 

Let's break it down. There are three things.
- The database (RethinkDB, thinky)
- More work on the API (like plugging it on the DB)
- A beginning of a front-end (either with React or a naive HTML/JS)

# Part I: the database

## Context
We can start working on the other two, but having a basic solid basis for the scheme would be cool. I'll try to find the model we used in an older chat project. We should also setup the DB (locally, but with a config file).

## To Do
- [ ] the scheme
- [x] [thinky](https://github.com/neumino/thinky) usage
- [x] DB connection setup

# Part II: the API

## Context
It's the purpose of this code: be an API for neko. So we should have more basic things, like signing in, get a list of users...
It also means the design of the koa app.

## To Do
- [ ] more controllers
- [ ] more routes
- [ ] more middleware
- [ ] more thinking (meh.)

# Part III: the front end

## Context
So we settled down on [React](https://facebook.github.io/react/), are we sure about this? If so, I'll initiate the git repo.
We'll use [`create-react-app`](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html), with a bit of config on the linter side (`xo` is back).

## To Do
- [x] check that React is fine
- [x] create repo
- [x] setup `create-react-app`

If we're good on this, I'll create some master issues to better define what we should do.

**Comment by justinrlle** [comment]
Everything was done for the front end in fact ([link](https://github.com/ShinGecko/neKo) to the repo)

**Comment by Shenrak** [comment]
What do you have in mind when you say "DB connection setup" ?

**Comment by justinrlle** [comment]
I was thinking of using a config file with defaults which we could check out in git, but overridable by another file, which can contain more sensitive information, but that we shouldn't checkout in git.

**Comment by justinrlle** [comment]
The overriding would be done by your [file](/ShinGecko/neKo-Api/blob/develop/app/utils/thinky.js), and there would be a file config.js ignored by git in the root directory.

**Comment by ViGrad** [comment]
Is that issue only about sprint 1 "Authentification" or about all project? I think it could be interesting to open a new issue for every sprint so everything will be easier to manage

**Comment by justinrlle** [comment]
Sprints, like real sprints? Like sprints of 4 weeks?
Or just milestones? Because milestones are already a feature of github, this issue was just brought up to get some kind of overview of what we want/need to do.

**Comment by ViGrad** [comment]
It depends about how you consider a sprint. To me, a sprint contains a list of tasks that we have to carry out to reach a milestone. 
Sure, a sprint is supposed to be static, but I think it's better if we allow ourselves the possibility to add some features and tasks to the task list.

So, to me, sprints and milestone are pretty the same

Anyway, it's always a good thing to have a to do list, so we will be sure to forget nothing. I don't know how milestones works, but why not start using them if they handle todos.
